[32m2024-12-09 20:09:36 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fe252d56-2cb2-4164-ad12-fa7d27bf19e8 - 22314 - LOGS_CAPTURED - Started capturing logs in process (pid: 22314).
[32m2024-12-09 20:09:36 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - fe252d56-2cb2-4164-ad12-fa7d27bf19e8 - 22314 - orders - STEP_START - Started execution of step "orders".
[32m2024-12-09 20:09:36 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - fe252d56-2cb2-4164-ad12-fa7d27bf19e8 - 22314 - orders - STEP_FAILURE - Execution of step "orders" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "orders"::

FileNotFoundError: [Errno 2] No such file or directory: '/Users/christian/code/30_days_of_dagster/30_days_dagster/orders_raw.csv'

Stack Trace:
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 482, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/30_days_dagster/30_days_dagster/09_day.py", line 62, in orders
    orders = pd.read_csv(os.path.join(config.file_path, 'orders_raw.csv'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/Users/christian/code/30_days_of_dagster/.venv/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
[0m
